spring:
  datasource:
    url: jdbc:mysql://soldout.cpiugfta2jm5.ap-northeast-2.rds.amazonaws.com:3306/tlover?
    autoReconnect: true
    username: admin
    password: mango1030
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    hibernate:
      ddl-auto: none
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        #default_batch_fetch_size: 100
    #open-in-view: false
    database-platform: org.hibernate.dialect.MySQL5Dialect

  security:
    oauth2:
      client:
        provider:
          naver:
            user-info_uri: https://openapi.naver.com/v1/nid/me
          kakao:
            user-info-uri: https://kapi.kakao.com/v2/user/me
          google:
            user-info_uri: https://oauth2.googleapis.com/tokeninfo

  jwt:
    access-key: xlavmfhwprxmzlddhkdHGFDHDFWkGDSHSdsjaHFGDHDnglamfekhgsdfeDFHGEG
    refresh-key: flvmfptlxhgDFSGHSDrzmsanjffhgkfHDFGwlahfmrpTekhDFGERRGVFDSG

cloud:
  aws:
    s3:
      bucket: tlover-backend-images
    credentials:
      access-key: AKIAVKTYRMM6ZHUARZRW
      secret-key: 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
    region:
      static: ap-northeast-2
    stack:
      auto: false

  sms:
    service-id: ncp:sms:kr:280044915694:infra-sms
    access-key: JUARhMRAzpFrstZqd775
    secret-key: lgiOpHwGvTW5HjcIaCKkhATBHFB3qeRuWzaBOrZZ


