spring:
  batch.job.enabled: false
  datasource:
     url: ENC(mVWQxgZgCFGWIUi3e9+NbXTvFW/PMBbQkoacJ5fF1chcpHh1Bq+NNhd67Kab9tC/nXXnP+YZOskNKJuJNEEZkaA+kVmuytig+vaAZipDhaejXZjeHiHVeg==)
    autoReconnect: true
    username: ENC(PrnaFLyVrZ8Z8yn8epXwsg==)
    password: ENC(vWB/yP4uFj2HDOHBebdyKxjDvecVbvTA)
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    initialize: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    hibernate:
      ddl-auto: create
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        #default_batch_fetch_size: 100
    #open-in-view: false
    database-platform: org.hibernate.dialect.MySQL5Dialect
    defer-datasource-initialization: true

  security:
    oauth2:
      client:
        provider:
          naver:
            user-info_uri: https://openapi.naver.com/v1/nid/me
          kakao:
            user-info-uri: https://kapi.kakao.com/v2/user/me
          google:
            user-info_uri: https://oauth2.googleapis.com/tokeninfo

  jwt:
    access-key: ENC(/5bz6CeOPbTevdJRJ1dACwQ40eDQTG3f6UkOfqKaGgY2KusDijH/TpY+Ct7n9gxK1Eos3aLBud2w2Q4kuEt0pk+bZXaOtIg4)
    refresh-key: ENC(NcfK+JjBpriO9BarU6/De4FPn1KA5Vv3p2dIuWp9wEyiaP+CBryWNj6A0cdw08iUwogHUgZqvXGjdN2LryL9K3rDtkwgLe2W)

cloud:
  aws:
    s3:
      bucket: tlover-bucket
    credentials:
      access-key: ENC(upZcdwbborEKHkDN8BZXVFFek0Ivj7Bz6/27iYDnQ3o=)
      secret-key: ENC(I7KCmkANZjPZA5ZkFyyWPXGeGnqmbh12N5m2gnvdavpFaXrJYKKb0qSacAepqq3AGpDLG6KPYAI=)
    region:
      static: ap-northeast-2
    stack:
      auto: false

sms:
  service-id: ENC(I7KCmkANZjPZA5ZkFyyWPXGeGnqmbh12N5m2gnvdavpFaXrJYKKb0qSacAepqq3AGpDLG6KPYAI=)
  access-key: ENC(YgrzqsLTImUcST0VM0vBLR6tn+6qwnoQwmDZpSmzxRY=)
  secret-key: ENC(/uyZ6F0d/D8pUX0NUvXBftLtvMBst06TDNru7Gg3MfYtPmUZ0N/dKrj0eBEXCtG2ZuTH8idgyMA=)

weather:
  service-key: ENC(AiCfffLKKgXfC5UWPvSyQyPgybtUu0tyK55DfuYfPl9SoadmIQo1Atj7L9J0p3zEKrdpEIBv7T+p6OMaDHmXKDG9dI9SYtPRuJk1/bRl2VszNLuAPatGZTtGcdvOBqKj4cKlyYM79Sud4V+iNeObpA==)


jasypt:
  encryptor:
    bean: jasyptEncyptor

