spring:
  batch.job.enabled: false
  datasource:
    url: jdbc:mysql://tloverdb.cjgvxgjzvddh.ap-northeast-2.rds.amazonaws.com:3306/tloverdb?
    autoReconnect: true
    username: tlover
    password: tlover123!!
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    initialize: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    hibernate:
      ddl-auto: update
    #      naming:
    #        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        #default_batch_fetch_size: 100
    #open-in-view: false
    database-platform: org.hibernate.dialect.MySQL5Dialect
    defer-datasource-initialization: true

  security:
    oauth2:
      client:
        provider:
          naver:
            user-info_uri: https://openapi.naver.com/v1/nid/me
          kakao:
            user-info-uri: https://kapi.kakao.com/v2/user/me
          google:
            user-info_uri: https://oauth2.googleapis.com/tokeninfo

  jwt:
    access-key: xlavmfhwprxmzlddhkdHGFDHDFWkGDSHSdsjaHFGDHDnglamfekhgsdfeDFHGEG
    refresh-key: flvmfptlxhgDFSGHSDrzmsanjffhgkfHDFGwlahfmrpTekhDFGERRGVFDSG

cloud:
  aws:
    s3:
      bucket: tlover-bucket
    credentials:
      access-key: AKIATHDBPLGZL6TVERDA
      secret-key: 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
    region:
      static: ap-northeast-2
    stack:
      auto: false

sms:
  service-id: ncp:sms:kr:280044915694:infra-sms
  access-key: JUARhMRAzpFrstZqd775
  secret-key: lgiOpHwGvTW5HjcIaCKkhATBHFB3qeRuWzaBOrZZ

weather:
  service-key: TafHkD6CilGs36dV%2B9czinbrrqD1AymCTtNo7U%2B9PpGxErWg76qqU7Iq0cRSqpi7lEbvLT872%2B19d6p0%2B7qE5g%3D%3D