spring:
  datasource:
<<<<<<< HEAD
    url: jdbc:mysql://localhost:3306/tlover?characterEncoding=utf8
    username: tlover
    password: tlover
=======
    url: jdbc:mysql://localhost:3306/trover?characterEncoding=utf8
    username: root
    password: root
>>>>>>> 89f3cf49d48a54f43e5c5c124d40d76c432a8c1b
    driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    hibernate:
      ddl-auto: create
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        #default_batch_fetch_size: 100
    #open-in-view: false
    database-platform: org.hibernate.dialect.MySQL5Dialect

  security:
    oauth2:
      client:
        provider:
          naver:
            user-info_uri: https://openapi.naver.com/v1/nid/me
